  GNU nano 4.8                                   metricbeat-playbook.yml                                             ---
- name: Install Metricbeat and copy the Metricbeat config files to WEBVM boxes
  hosts: webservers
  remote_user: ansible
  become: true
  tasks:
    # Download the Metricbeat file from artifacts.elastic.co
    - name: Download deb files from artifacts.elastic.co
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

    # Install the deb file using the dpkg command
    - name: Install deb using dpkg
      command: dpkg -i metricbeat-7.6.1-amd64.deb

    # Copy Metricbeat config from your ansible container to WEBVM
    - name: Copy Metricbeat config to YML file
      copy:
        src: /etc/ansible/files/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml

    # Run the Metricbeat modules enable docker command
    - name: running the Metricbeat modules enable docker command
      command: metricbeat modules enable docker

    # Setup Metricbeat
    - name: setup Metricbeat
      command: sudo metricbeat setup

    # Start Metricbeat
    - name: starting Metricbeat
      command: sudo service metricbeat start

    # Enable Metricbeat on start
    - name: enabling Metricbeat on startup
      systemd:
        name: metricbeat
        enabled: yes
